import json
import math
import os
from typing import Dict

from logger import logger


class ConfidenceCalibrator:
    """
    Calibrates raw detector confidence scores into probabilities that are
    comparable across agents, using per-agent Platt scaling (1D logistic
    regression):

        calibrated_score = sigmoid(a * raw_score + b)

    Each agent's detector (MathDetector, CodeDetector, ...) produces a raw
    score in [0, 1] via hand-tuned additive heuristics on a DIFFERENT scale
    (different keyword counts, different base offsets, different numbers of
    contributing signals). A raw score of 0.7 from one detector and 0.7 from
    another are not directly comparable as probabilities. Platt scaling
    learns, per agent, the affine transform (in logit space) that best maps
    that agent's raw score onto P(this agent is the correct route), fit on a
    labeled dataset of (query, gold_agent) pairs.

    Parameters (a, b) are loaded from `calibration_params.json`
    (generated by calibration/train_calibrator.py). If that file is
    missing, or an agent has no entry, the calibrator falls back to the
    identity transform (calibrated_score = raw_score), which is exactly the
    old no-op behaviour -- so the system degrades gracefully if no
    calibration data exists, but uses real, fitted parameters whenever it
    does.

    To retrain (e.g. after adding more labeled examples to
    calibration/labeled_queries.json or accumulating routing telemetry):

        python calibration/train_calibrator.py
    """

    DEFAULT_PARAMS_PATH = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "calibration_params.json"
    )

    def __init__(self, params_path: str = None):
        self.params_path = params_path or self.DEFAULT_PARAMS_PATH
        self.params: Dict[str, Dict[str, float]] = {}
        self._load_params()

    def _load_params(self):
        if not os.path.exists(self.params_path):
            logger.warning(
                f"[ConfidenceCalibrator] No calibration params found at "
                f"{self.params_path}. Falling back to identity calibration "
                f"(raw_score == calibrated_score) for all agents. "
                f"Run `python calibration/train_calibrator.py` to fit real "
                f"Platt-scaling parameters from calibration/labeled_queries.json."
            )
            self.params = {}
            return

        try:
            with open(self.params_path, "r", encoding="utf-8") as f:
                loaded = json.load(f)
            # Basic validation: each entry must have numeric 'a' and 'b'.
            self.params = {
                agent: {"a": float(v["a"]), "b": float(v["b"])}
                for agent, v in loaded.items()
                if isinstance(v, dict) and "a" in v and "b" in v
            }
            logger.info(
                f"[ConfidenceCalibrator] Loaded Platt-scaling parameters for "
                f"{len(self.params)} agents from {self.params_path}"
            )
        except Exception as e:
            logger.error(
                f"[ConfidenceCalibrator] Failed to load calibration params "
                f"from {self.params_path}: {e}. Falling back to identity calibration."
            )
            self.params = {}

    @staticmethod
    def _sigmoid(z: float) -> float:
        if z >= 0:
            ez = math.exp(-z)
            return 1.0 / (1.0 + ez)
        else:
            ez = math.exp(z)
            return ez / (1.0 + ez)

    def calibrate(self, raw_scores: Dict[str, float]) -> Dict[str, float]:
        """
        Applies per-agent Platt-scaling to raw confidence scores.

        calibrated[agent] = sigmoid(a * raw_scores[agent] + b)

        If no fitted (a, b) exist for an agent, that agent's score passes
        through unchanged (true identity pass-through, rather than running
        it through a sigmoid it was never fit for).
        """
        calibrated = {}
        for agent_name, raw_score in raw_scores.items():
            raw_score = max(0.0, min(1.0, float(raw_score)))
            agent_params = self.params.get(agent_name)
            if agent_params is None:
                calibrated[agent_name] = raw_score
                continue
            a, b = agent_params["a"], agent_params["b"]
            calibrated[agent_name] = self._sigmoid(a * raw_score + b)
        return calibrated

    def reload(self):
        """Re-read calibration_params.json from disk (e.g. after retraining)."""
        self._load_params()